CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE asp_net_roles (
        id text NOT NULL,
        name character varying(256),
        normalized_name character varying(256),
        concurrency_stamp text,
        CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE asp_net_users (
        id text NOT NULL,
        nome_completo character varying(255),
        cpf text,
        ativo boolean NOT NULL,
        data_criacao timestamp with time zone NOT NULL,
        user_name character varying(256),
        normalized_user_name character varying(256),
        email character varying(256),
        normalized_email character varying(256),
        email_confirmed boolean NOT NULL,
        password_hash text,
        security_stamp text,
        concurrency_stamp text,
        phone_number text,
        phone_number_confirmed boolean NOT NULL,
        two_factor_enabled boolean NOT NULL,
        lockout_end timestamp with time zone,
        lockout_enabled boolean NOT NULL,
        access_failed_count integer NOT NULL,
        CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_adicional (
        id_adicional integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(50) NOT NULL,
        valor_diaria numeric(10,2) NOT NULL,
        ativo boolean NOT NULL,
        CONSTRAINT pk_tb_adicional PRIMARY KEY (id_adicional)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_categoria_veiculo (
        id_categoria integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(50) NOT NULL,
        valor_diaria numeric(10,2) NOT NULL,
        limite_km integer,
        valor_km_excedente numeric(10,2),
        CONSTRAINT pk_tb_categoria_veiculo PRIMARY KEY (id_categoria)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_cliente_historico (
        id_historico integer GENERATED BY DEFAULT AS IDENTITY,
        id_cliente integer NOT NULL,
        data_evento timestamp with time zone NOT NULL,
        acao text,
        usuario_evento text,
        numero_habilitacao text,
        validade_habilitacao timestamp with time zone,
        total_locacoes integer NOT NULL,
        id_usuario_modificacao text,
        CONSTRAINT pk_tb_cliente_historico PRIMARY KEY (id_historico)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_seguro (
        id_seguro integer GENERATED BY DEFAULT AS IDENTITY,
        descricao character varying(100) NOT NULL,
        nome character varying(45) NOT NULL,
        valor_diaria numeric(10,2) NOT NULL,
        franquia numeric NOT NULL,
        cobertura character varying(200) NOT NULL,
        ativo boolean NOT NULL,
        CONSTRAINT pk_tb_seguro PRIMARY KEY (id_seguro)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_user_historico (
        id_historico integer GENERATED BY DEFAULT AS IDENTITY,
        id text,
        nome_completo text,
        email text,
        phone_number text,
        data_evento timestamp with time zone NOT NULL,
        acao text,
        usuario_evento text,
        CONSTRAINT pk_tb_user_historico PRIMARY KEY (id_historico)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE asp_net_role_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        role_id text NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
        CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE asp_net_user_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id text NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
        CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE asp_net_user_logins (
        login_provider text NOT NULL,
        provider_key text NOT NULL,
        provider_display_name text,
        user_id text NOT NULL,
        CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
        CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE asp_net_user_roles (
        user_id text NOT NULL,
        role_id text NOT NULL,
        CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
        CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE,
        CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE asp_net_user_tokens (
        user_id text NOT NULL,
        login_provider text NOT NULL,
        name text NOT NULL,
        value text,
        CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
        CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE refresh_tokens (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        token text NOT NULL,
        expira_em timestamp with time zone NOT NULL,
        revogado boolean NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        user_id text NOT NULL,
        CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
        CONSTRAINT fk_refresh_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_cliente (
        id_cliente integer GENERATED BY DEFAULT AS IDENTITY,
        numero_habilitacao text,
        validade_habilitacao timestamp with time zone,
        ativo boolean NOT NULL,
        total_locacoes integer NOT NULL,
        status character varying(20) NOT NULL,
        data_criacao timestamp with time zone NOT NULL,
        id_usuario_criacao text,
        data_modificacao timestamp with time zone,
        id_usuario_modificacao text,
        id_asp_net_users text NOT NULL,
        CONSTRAINT pk_tb_cliente PRIMARY KEY (id_cliente),
        CONSTRAINT fk_tb_cliente_users_id_asp_net_users FOREIGN KEY (id_asp_net_users) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_funcionario (
        id_funcionario integer GENERATED BY DEFAULT AS IDENTITY,
        matricula character varying(20) NOT NULL,
        cargo character varying(50),
        status boolean NOT NULL,
        id_user text NOT NULL,
        CONSTRAINT pk_tb_funcionario PRIMARY KEY (id_funcionario),
        CONSTRAINT fk_tb_funcionario_users_id_user FOREIGN KEY (id_user) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_foto_categoria_veiculo (
        id_foto integer GENERATED BY DEFAULT AS IDENTITY,
        id_categoria_veiculo integer,
        nome_arquivo text,
        raiz text,
        diretorio text,
        extensao text,
        quantidade_bytes bigint,
        data_upload timestamp with time zone NOT NULL,
        CONSTRAINT pk_tb_foto_categoria_veiculo PRIMARY KEY (id_foto),
        CONSTRAINT fk_tb_foto_categoria_veiculo_tb_categoria_veiculo_id_categoria FOREIGN KEY (id_categoria_veiculo) REFERENCES tb_categoria_veiculo (id_categoria) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_endereco (
        id_endereco integer GENERATED BY DEFAULT AS IDENTITY,
        id_cliente integer,
        logradouro text NOT NULL,
        numero text NOT NULL,
        complemento text,
        bairro text NOT NULL,
        cidade text NOT NULL,
        estado text NOT NULL,
        cep text NOT NULL,
        CONSTRAINT pk_tb_endereco PRIMARY KEY (id_endereco),
        CONSTRAINT fk_tb_endereco_tb_cliente_id_cliente FOREIGN KEY (id_cliente) REFERENCES tb_cliente (id_cliente) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_filial (
        id_filial integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        cidade character varying(100) NOT NULL,
        ativo boolean NOT NULL,
        id_endereco integer NOT NULL,
        CONSTRAINT pk_tb_filial PRIMARY KEY (id_filial),
        CONSTRAINT fk_tb_filial_tb_endereco_id_endereco FOREIGN KEY (id_endereco) REFERENCES tb_endereco (id_endereco) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_foto_filial (
        id_foto integer GENERATED BY DEFAULT AS IDENTITY,
        id_filial integer,
        nome_arquivo text,
        raiz text,
        diretorio text,
        extensao text,
        quantidade_bytes bigint,
        data_upload timestamp with time zone NOT NULL,
        CONSTRAINT pk_tb_foto_filial PRIMARY KEY (id_foto),
        CONSTRAINT fk_tb_foto_filial_tb_filial_id_filial FOREIGN KEY (id_filial) REFERENCES tb_filial (id_filial) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_reserva (
        id_reserva integer GENERATED BY DEFAULT AS IDENTITY,
        id_cliente integer NOT NULL,
        id_categoria_veiculo integer NOT NULL,
        id_filial integer NOT NULL,
        data_inicio timestamp with time zone NOT NULL,
        data_fim timestamp with time zone NOT NULL,
        status integer NOT NULL,
        ativo boolean NOT NULL,
        CONSTRAINT pk_tb_reserva PRIMARY KEY (id_reserva),
        CONSTRAINT fk_tb_reserva_tb_categoria_veiculo_id_categoria_veiculo FOREIGN KEY (id_categoria_veiculo) REFERENCES tb_categoria_veiculo (id_categoria) ON DELETE RESTRICT,
        CONSTRAINT fk_tb_reserva_tb_cliente_id_cliente FOREIGN KEY (id_cliente) REFERENCES tb_cliente (id_cliente) ON DELETE RESTRICT,
        CONSTRAINT fk_tb_reserva_tb_filial_id_filial FOREIGN KEY (id_filial) REFERENCES tb_filial (id_filial) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_veiculo (
        id_veiculo integer GENERATED BY DEFAULT AS IDENTITY,
        placa character varying(10) NOT NULL,
        marca text NOT NULL,
        modelo text NOT NULL,
        ano integer NOT NULL,
        chassi character varying(30) NOT NULL,
        id_categoria integer NOT NULL,
        km_atual integer NOT NULL,
        ativo boolean NOT NULL,
        disponivel boolean NOT NULL,
        id_filial_atual integer NOT NULL,
        status integer NOT NULL,
        CONSTRAINT pk_tb_veiculo PRIMARY KEY (id_veiculo),
        CONSTRAINT fk_tb_veiculo_tb_categoria_veiculo_id_categoria FOREIGN KEY (id_categoria) REFERENCES tb_categoria_veiculo (id_categoria) ON DELETE RESTRICT,
        CONSTRAINT fk_tb_veiculo_tb_filial_filial_atual_id FOREIGN KEY (id_filial_atual) REFERENCES tb_filial (id_filial) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_locacao (
        id_locacao integer GENERATED BY DEFAULT AS IDENTITY,
        id_cliente integer NOT NULL,
        id_veiculo integer NOT NULL,
        id_funcionario integer NOT NULL,
        id_filial_retirada integer NOT NULL,
        id_filial_devolucao integer,
        data_inicio timestamp with time zone NOT NULL,
        data_fim_prevista timestamp with time zone NOT NULL,
        data_fim_real timestamp with time zone,
        km_inicial integer NOT NULL,
        km_final integer,
        valor_previsto numeric(10,2) NOT NULL,
        valor_final numeric(10,2),
        status character varying(20) NOT NULL,
        CONSTRAINT pk_tb_locacao PRIMARY KEY (id_locacao),
        CONSTRAINT fk_tb_locacao_tb_cliente_cliente_id FOREIGN KEY (id_cliente) REFERENCES tb_cliente (id_cliente) ON DELETE RESTRICT,
        CONSTRAINT fk_tb_locacao_tb_filial_id_filial_devolucao FOREIGN KEY (id_filial_devolucao) REFERENCES tb_filial (id_filial) ON DELETE RESTRICT,
        CONSTRAINT fk_tb_locacao_tb_filial_id_filial_retirada FOREIGN KEY (id_filial_retirada) REFERENCES tb_filial (id_filial) ON DELETE RESTRICT,
        CONSTRAINT fk_tb_locacao_tb_funcionario_id_funcionario FOREIGN KEY (id_funcionario) REFERENCES tb_funcionario (id_funcionario) ON DELETE RESTRICT,
        CONSTRAINT fk_tb_locacao_tb_veiculo_id_veiculo FOREIGN KEY (id_veiculo) REFERENCES tb_veiculo (id_veiculo) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_manutencao (
        id_manutencao integer GENERATED BY DEFAULT AS IDENTITY,
        tipo_manutencao integer NOT NULL,
        descricao text,
        custo numeric(10,2) NOT NULL,
        data_inicio timestamp with time zone NOT NULL,
        data_fim timestamp with time zone,
        status_manutencao integer NOT NULL,
        id_veiculo integer,
        CONSTRAINT pk_tb_manutencao PRIMARY KEY (id_manutencao),
        CONSTRAINT fk_tb_manutencao_tb_veiculo_id_veiculo FOREIGN KEY (id_veiculo) REFERENCES tb_veiculo (id_veiculo) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE historico_status_locacao (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_locacao integer NOT NULL,
        status character varying(20) NOT NULL,
        data_status timestamp with time zone NOT NULL,
        id_funcionario integer NOT NULL,
        locacao_id_locacao integer NOT NULL,
        CONSTRAINT pk_historico_status_locacao PRIMARY KEY (id),
        CONSTRAINT fk_historico_status_locacao_tb_funcionario_id_funcionario FOREIGN KEY (id_funcionario) REFERENCES tb_funcionario (id_funcionario) ON DELETE CASCADE,
        CONSTRAINT fk_historico_status_locacao_tb_locacao_locacao_id_locacao FOREIGN KEY (locacao_id_locacao) REFERENCES tb_locacao (id_locacao) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_caucao (
        id_caucao integer GENERATED BY DEFAULT AS IDENTITY,
        valor numeric(10,2) NOT NULL,
        status character varying(20) NOT NULL,
        id_locacao integer,
        CONSTRAINT pk_tb_caucao PRIMARY KEY (id_caucao),
        CONSTRAINT fk_tb_caucao_tb_locacao_id_locacao FOREIGN KEY (id_locacao) REFERENCES tb_locacao (id_locacao) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_locacao_adicional (
        id_locacao_adicional integer GENERATED BY DEFAULT AS IDENTITY,
        id_adicional integer NOT NULL,
        id_locacao integer NOT NULL,
        valor_diaria numeric NOT NULL,
        valor_total numeric NOT NULL,
        quantidade integer NOT NULL,
        dias integer NOT NULL,
        CONSTRAINT pk_tb_locacao_adicional PRIMARY KEY (id_locacao_adicional),
        CONSTRAINT fk_tb_locacao_adicional_tb_adicional_id_adicional FOREIGN KEY (id_adicional) REFERENCES tb_adicional (id_adicional) ON DELETE CASCADE,
        CONSTRAINT fk_tb_locacao_adicional_tb_locacao_id_locacao FOREIGN KEY (id_locacao) REFERENCES tb_locacao (id_locacao) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_locacao_seguro (
        id_locacao_seguro integer GENERATED BY DEFAULT AS IDENTITY,
        id_locacao integer NOT NULL,
        id_seguro integer NOT NULL,
        ativo boolean NOT NULL,
        CONSTRAINT pk_tb_locacao_seguro PRIMARY KEY (id_locacao_seguro),
        CONSTRAINT fk_tb_locacao_seguro_tb_locacao_id_locacao FOREIGN KEY (id_locacao) REFERENCES tb_locacao (id_locacao) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_multa (
        id_multa integer GENERATED BY DEFAULT AS IDENTITY,
        tipo character varying(20) NOT NULL,
        valor numeric(10,2) NOT NULL,
        status character varying(20) NOT NULL,
        id_locacao integer,
        CONSTRAINT pk_tb_multa PRIMARY KEY (id_multa),
        CONSTRAINT fk_tb_multa_tb_locacao_id_locacao FOREIGN KEY (id_locacao) REFERENCES tb_locacao (id_locacao) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_pagamento (
        id_pagamento integer GENERATED BY DEFAULT AS IDENTITY,
        valor numeric(10,2) NOT NULL,
        data_pagamento timestamp with time zone NOT NULL,
        status text NOT NULL,
        id_forma_pagamento integer NOT NULL,
        id_locacao integer NOT NULL,
        CONSTRAINT pk_tb_pagamento PRIMARY KEY (id_pagamento),
        CONSTRAINT fk_tb_pagamento_tb_locacao_id_locacao FOREIGN KEY (id_locacao) REFERENCES tb_locacao (id_locacao) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_vistoria (
        id_vistoria integer GENERATED BY DEFAULT AS IDENTITY,
        id_locacao integer NOT NULL,
        tipo integer NOT NULL,
        nivel_combustivel integer NOT NULL,
        observacoes text,
        data_vistoria timestamp with time zone NOT NULL,
        id_funcionario integer NOT NULL,
        km_veiculo integer NOT NULL,
        CONSTRAINT pk_tb_vistoria PRIMARY KEY (id_vistoria),
        CONSTRAINT fk_tb_vistoria_tb_funcionario_id_funcionario FOREIGN KEY (id_funcionario) REFERENCES tb_funcionario (id_funcionario) ON DELETE CASCADE,
        CONSTRAINT fk_tb_vistoria_tb_locacao_id_locacao FOREIGN KEY (id_locacao) REFERENCES tb_locacao (id_locacao) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_dano (
        id_dano integer GENERATED BY DEFAULT AS IDENTITY,
        id_vistoria integer NOT NULL,
        descricao character varying(200) NOT NULL,
        tipo_dano integer NOT NULL,
        valor_estimado numeric(10,2) NOT NULL,
        tipo_status integer NOT NULL,
        data_registro timestamp with time zone NOT NULL,
        CONSTRAINT pk_tb_dano PRIMARY KEY (id_dano),
        CONSTRAINT fk_tb_dano_tb_vistoria_id_vistoria FOREIGN KEY (id_vistoria) REFERENCES tb_vistoria (id_vistoria) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE TABLE tb_foto_vistoria (
        id_foto integer GENERATED BY DEFAULT AS IDENTITY,
        id_vistoria integer,
        nome_arquivo text,
        raiz text,
        diretorio text,
        extensao text,
        quantidade_bytes bigint,
        data_upload timestamp with time zone NOT NULL,
        CONSTRAINT pk_tb_foto_vistoria PRIMARY KEY (id_foto),
        CONSTRAINT fk_tb_foto_vistoria_tb_vistoria_id_vistoria FOREIGN KEY (id_vistoria) REFERENCES tb_vistoria (id_vistoria) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_asp_net_role_claims_role_id ON asp_net_role_claims (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON asp_net_roles (normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_asp_net_user_claims_user_id ON asp_net_user_claims (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_asp_net_user_logins_user_id ON asp_net_user_logins (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_asp_net_user_roles_role_id ON asp_net_user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX "EmailIndex" ON asp_net_users (normalized_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON asp_net_users (normalized_user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_historico_status_locacao_id_funcionario ON historico_status_locacao (id_funcionario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_historico_status_locacao_locacao_id_locacao ON historico_status_locacao (locacao_id_locacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_refresh_tokens_token ON refresh_tokens (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_caucao_id_locacao ON tb_caucao (id_locacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_tb_cliente_id_asp_net_users ON tb_cliente (id_asp_net_users);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_dano_id_vistoria ON tb_dano (id_vistoria);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_tb_endereco_id_cliente ON tb_endereco (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_tb_filial_id_endereco ON tb_filial (id_endereco);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_foto_categoria_veiculo_id_categoria_veiculo ON tb_foto_categoria_veiculo (id_categoria_veiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_foto_filial_id_filial ON tb_foto_filial (id_filial);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_foto_vistoria_id_vistoria ON tb_foto_vistoria (id_vistoria);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_tb_funcionario_id_user ON tb_funcionario (id_user);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_tb_funcionario_matricula ON tb_funcionario (matricula);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_cliente_id ON tb_locacao (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_id_filial_devolucao ON tb_locacao (id_filial_devolucao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_id_filial_retirada ON tb_locacao (id_filial_retirada);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_id_funcionario ON tb_locacao (id_funcionario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_id_veiculo ON tb_locacao (id_veiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_adicional_id_adicional ON tb_locacao_adicional (id_adicional);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_adicional_id_locacao ON tb_locacao_adicional (id_locacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_locacao_seguro_id_locacao ON tb_locacao_seguro (id_locacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_manutencao_id_veiculo ON tb_manutencao (id_veiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_multa_id_locacao ON tb_multa (id_locacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_pagamento_id_locacao ON tb_pagamento (id_locacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_reserva_id_categoria_veiculo ON tb_reserva (id_categoria_veiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_reserva_id_cliente ON tb_reserva (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_reserva_id_filial ON tb_reserva (id_filial);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_tb_veiculo_chassi ON tb_veiculo (chassi);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_veiculo_filial_atual_id ON tb_veiculo (id_filial_atual);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_veiculo_id_categoria ON tb_veiculo (id_categoria);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE UNIQUE INDEX ix_tb_veiculo_placa ON tb_veiculo (placa);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_vistoria_id_funcionario ON tb_vistoria (id_funcionario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    CREATE INDEX ix_tb_vistoria_id_locacao ON tb_vistoria (id_locacao);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807115533_Inicial') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260807115533_Inicial', '8.0.22');
    END IF;
END $EF$;
COMMIT;

